# Generated by Django 5.2.4 on 2025-09-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_transaction_account_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='cash', max_length=100),
        ),
    ]
